# Generated by Django 4.1.7 on 2023-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('privacy', models.CharField(choices=[('1', 'public'), ('2', 'private')], max_length=2)),
            ],
        ),
    ]
