# Generated by Django 4.1.7 on 2023-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon1', '0003_alter_products_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='privacy',
            field=models.CharField(choices=[('1', 'public'), ('2', 'private')], max_length=2, null=True),
        ),
    ]
