# Generated by Django 3.2.12 on 2023-03-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
        ('amazon1', '0007_auto_20230304_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='NewProducts',
        ),
    ]
