# Generated by Django 4.1.7 on 2023-03-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
        ('amazon1', '0008_rename_products_newproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='privacy',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('privacy', models.CharField(choices=[('1', 'public'), ('2', 'private')], max_length=2, null=True)),
                ('image', models.ImageField(upload_to='photos/images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='category.category')),
            ],
        ),
    ]
