# Generated by Django 4.1.7 on 2023-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon1', '0010_newproducts_image_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='image',
        ),
        migrations.AddField(
            model_name='newproducts',
            name='privacy',
            field=models.CharField(choices=[('1', 'public'), ('2', 'private')], max_length=2, null=True),
        ),
    ]
