# Generated by Django 4.1.7 on 2023-03-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
        ('amazon1', '0012_newproducts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='image',
        ),
        migrations.AddField(
            model_name='newproducts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='category.category'),
        ),
    ]
