# Generated by Django 4.1.7 on 2023-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon1', '0013_remove_newproducts_image_newproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/images'),
            preserve_default=False,
        ),
    ]
